### ISSUE TITLE
如何解决跨域问题，请列举你的方案。

### ISSUE THREAD

**Issue by coxo** [N-ZOO/everycode#11]
前端跨域解决方案比较多，根据工作经验，列举你遇到的问题，以及解决方案。谢谢。

**Comment by langmao** [comment]
- 从最不常用的开始——图像ping 
  
  [具体原理，实现——传送门](http://www.tuicool.com/articles/fMvii2)

**Comment by bailnl** [comment]
自己的服务器开个大招就好了 允许指定的跨域

**Comment by VaJoy** [comment]
泛问题讨论不该出在everycode，关闭

**Comment by coxo** [comment]
讨论性的不出现在这里吗
